### ISSUE TITLE
searchPickupPoints & searchPickupPointsByText do not return an empty array

### ISSUE THREAD

**Issue by k1sul1** [Pakettikauppa/api-library#11]
... they return a string that looks like an array when you print to the error log. 

https://github.com/Pakettikauppa/api-library/commit/a7a7084d963ef36d08103c5092523e2d13433200

It's been in the code for two years now and fixing it is going to "break" like all integrations made on top of this library, but it should be fixed nevertheless. Nobody wants to do error / empty result handling based on `'[]'`, especially when the methods normally return arrays.

**Comment by joosev** [comment]
function is not returning arrays but json-text. But in 2.x release that will be fixed and returning objects/arrays always (== running json_decode in the library). It will be first fixed in dev-branch.
